# RATINGS PREDICTION PROJECT

In [12]:
conda install -c conda-forge/label/gcc7 missingno

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\jishn\anaconda3

  added / updated specs:
    - missingno


The following packages will be downloaded:

Note: you may need to restart the kernel to use updated packages.
    package                    |            build
    ---------------------------|-----------------
    conda-4.13.0               |   py38haa95532_0         926 KB
    missingno-0.4.1            |             py_0          10 KB  conda-forge/label/gcc7
    ------------------------------------------------------------
                                           Total:         936 KB

The following NEW packages will be INSTALLED:

  missingno          conda-forge/label/gcc7/noarch::missingno-0.4.1-py_0

The following packages will be UPDATED:

  conda                               4.10.1-py38haa95532_1 --> 4.13.0-py38haa95532_0




missingno-0.4.1      | 10 KB     |            |   0% 
missingno-0.4.1      | 10 KB     | ##########

In [17]:
conda install -c conda-forge pandas-profiling

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\jishn\anaconda3

  added / updated specs:
    - pandas-profiling


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.13.0               |   py38haa244fe_1        1016 KB  conda-forge
    pandas-profiling-1.4.1     |                0          40 KB  conda-forge
    python_abi-3.8             |           2_cp38           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.0 MB

The following NEW packages will be INSTALLED:

  pandas-profiling   conda-forge/win-64::pandas-profiling-1.4.1-0
  python_abi         conda-forge/win-64::python_abi-3.8-2_cp38

The following packages will be UPDATED:

  conda              pkgs/main::conda-4.13.0-py38haa95532_0 --> conda-forge::conda-4.13.0-py38haa244fe_1




con

In [19]:
pip install markupsafe==2.0.1

  Attempting uninstall: markupsafe
    Found existing installation: MarkupSafe 2.1.1
    Uninstalling MarkupSafe-2.1.1:
      Successfully uninstalled MarkupSafe-2.1.1
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\jishn\\anaconda3\\Lib\\site-packages\\~-rkupsafe\\_speedups.cp38-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



In [3]:
pip install scikit-plot

Note: you may need to restart the kernel to use updated packages.


In [2]:
!pip install lightgbm

In [2]:
conda install -c conda-forge xgboost

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\jishn\anaconda3

  added / updated specs:
    - xgboost


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _py-xgboost-mutex-2.0      |            cpu_0          11 KB  conda-forge
    libxgboost-1.5.1           |   cpu_h110a20b_2         2.3 MB  conda-forge
    py-xgboost-1.5.1           |cpu_py38hc22ac66_2         151 KB  conda-forge
    xgboost-1.5.1              |cpu_py38hc22ac66_2          13 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.5 MB

The following NEW packages will be INSTALLED:

  _py-xgboost-mutex  conda-forge/win-64::_py-xgboost-mutex-2.0-cpu_0
  libxgboost         conda-forge/win-64::libxgboost-1.5.1-cpu_h110a20b_2
  py-xgboost         conda-forge/win-64::py-xgboost-1.5.1-cpu_py38hc22

In [1]:
# IMPORTING PACKAGES

import pandas as pd # data processing
import numpy as np # working with arrays
import matplotlib.pyplot as plt # visualization
import seaborn as sns # visualization
import mpl_toolkits
%matplotlib inline
# Importing nltk libraries
import re
import string
import missingno
import pandas_profiling
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('averaged_perceptron_tagger', quiet=True)
from nltk import FreqDist
from nltk.tokenize import word_tokenize
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk import FreqDist

from scipy import stats
from scipy.stats import zscore
from scipy.sparse import hstack
import scikitplot as skplt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV 
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score, precision_score, confusion_matrix, accuracy_score, classification_report

from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.linear_model import LogisticRegression
from lightgbm import LGBMClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost.sklearn import XGBClassifier

import warnings
warnings.simplefilter("ignore")
warnings.filterwarnings("ignore")
import joblib

lemmatizer = nltk.stem.WordNetLemmatizer()

In [2]:
path='C:/Users/jishn/OneDrive/Desktop/Rating Prediction Project/flipkart1_reviews.csv'

In [3]:
df =pd.read_csv(path)
df

Unnamed: 0           Review_title  \
0               0              Excellent   
1               1  Mind-blowing purchase   
2               2         Simply awesome   
3               3           Nice product   
4               4        Worth the money   
...           ...                    ...   
21697       21697              Just okay   
21698       21698   Good quality product   
21699       21699           Does the job   
21700       21700              Just okay   
21701       21701   Good quality product   

                                             Review_text  Ratings  
0      Damnnn this product is just amazing. Super smo...        5  
1      Very good laptop with stylish and compact desi...        5  
2      Really much good and. Works faster, excellent ...        5  
3      Everything is fine\nDisplay is awesome 8k vide...        4  
4      Product has good screen but average build qual...        4  
...                                                  ...      ...  
21697                                            Average        3  
21698  Nice product but read full information because...        4  
21699                                   This is not good        3  
21700                                            Average        3  
21701  Nice product but read full information because...        4  

[21702 rows x 4 columns]

In [4]:
df.drop(columns = 'Unnamed: 0', inplace = True)
print("We have {} Rows and {} Columns in our dataframe".format(df.shape[0], df.shape[1]))
df.head(20)

We have 21702 Rows and 3 Columns in our dataframe


Review_title                                        Review_text  \
0               Excellent  Damnnn this product is just amazing. Super smo...   
1   Mind-blowing purchase  Very good laptop with stylish and compact desi...   
2          Simply awesome  Really much good and. Works faster, excellent ...   
3            Nice product  Everything is fine\nDisplay is awesome 8k vide...   
4         Worth the money  Product has good screen but average build qual...   
5            Does the job  Packing is not good,not pre installed window,D...   
6                 Awesome               Excellent product and good quality..   
7        Perfect product!                                  Very good product   
8               Very Good  Smooth performance, good for daily and casual ...   
9                 Awesome                                               Good   
10              Excellent  Damnnn this product is just amazing. Super smo...   
11  Mind-blowing purchase  Very good laptop with stylish and compact desi...   
12         Simply awesome  Really much good and. Works faster, excellent ...   
13           Nice product  Everything is fine\nDisplay is awesome 8k vide...   
14        Worth the money  Product has good screen but average build qual...   
15           Does the job  Packing is not good,not pre installed window,D...   
16                Awesome               Excellent product and good quality..   
17       Perfect product!                                  Very good product   
18              Very Good  Smooth performance, good for daily and casual ...   
19                Awesome                                               Good   

    Ratings  
0         5  
1         5  
2         5  
3         4  
4         4  
5         3  
6         5  
7         5  
8         4  
9         5  
10        5  
11        5  
12        5  
13        4  
14        4  
15        3  
16        5  
17        5  
18        4  
19        5

In [5]:
df.isna().sum() # checking for missing values

Review_title    0
Review_text     0
Ratings         0
dtype: int64

In [6]:
missingno.matrix(df, figsize = (15,8), color=(0.25, 0.75, 0.25), fontsize=18)

<AxesSubplot:>

In [7]:
print("We have {} Rows and {} Columns in our dataframe before removing NaN".format(df.shape[0], df.shape[1]))
df.dropna(inplace=True)
print("We have {} Rows and {} Columns in our dataframe after removing NaN".format(df.shape[0], df.shape[1]))

We have 21702 Rows and 3 Columns in our dataframe before removing NaN
We have 21702 Rows and 3 Columns in our dataframe after removing NaN


In [8]:
df.isnull().sum()

Review_title    0
Review_text     0
Ratings         0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21702 entries, 0 to 21701
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Review_title  21702 non-null  object
 1   Review_text   21702 non-null  object
 2   Ratings       21702 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 678.2+ KB


In [10]:
df['Ratings'].unique()

array([5, 4, 3, 1, 2], dtype=int64)

In [11]:
df['Ratings'] = df['Ratings'].replace('1.0 out of 5 stars',1)
df['Ratings'] = df['Ratings'].replace('2.0 out of 5 stars',2)
df['Ratings'] = df['Ratings'].replace('3.0 out of 5 stars',3)
df['Ratings'] = df['Ratings'].replace('4.0 out of 5 stars',4)
df['Ratings'] = df['Ratings'].replace('5.0 out of 5 stars',5)
df['Ratings'] = df['Ratings'].astype('int')
df['Ratings'].unique()

array([5, 4, 3, 1, 2])

In [12]:
# Now combining the "Review_title" and "Review_text" columns into one single column called "Review"
df['Review'] = df['Review_title'].map(str)+' '+df['Review_text']
df

Review_title  \
0                  Excellent   
1      Mind-blowing purchase   
2             Simply awesome   
3               Nice product   
4            Worth the money   
...                      ...   
21697              Just okay   
21698   Good quality product   
21699           Does the job   
21700              Just okay   
21701   Good quality product   

                                             Review_text  Ratings  \
0      Damnnn this product is just amazing. Super smo...        5   
1      Very good laptop with stylish and compact desi...        5   
2      Really much good and. Works faster, excellent ...        5   
3      Everything is fine\nDisplay is awesome 8k vide...        4   
4      Product has good screen but average build qual...        4   
...                                                  ...      ...   
21697                                            Average        3   
21698  Nice product but read full information because...        4   
21699                                   This is not good        3   
21700                                            Average        3   
21701  Nice product but read full information because...        4   

                                                  Review  
0      Excellent Damnnn this product is just amazing....  
1      Mind-blowing purchase Very good laptop with st...  
2      Simply awesome Really much good and. Works fas...  
3      Nice product Everything is fine\nDisplay is aw...  
4      Worth the money Product has good screen but av...  
...                                                  ...  
21697                                  Just okay Average  
21698  Good quality product Nice product but read ful...  
21699                      Does the job This is not good  
21700                                  Just okay Average  
21701  Good quality product Nice product but read ful...  

[21702 rows x 4 columns]

In [13]:
df['Review'][0]

'Excellent Damnnn this product is just amazing. Super smooth and water like display. Loved it.'

Text Processing to remove unwanted punctuations and special characters

In [14]:
'''Here I am defining a function to replace some of the contracted words to their full form and removing urls and some 
unwanted text'''

def decontracted(text):
    text = re.sub(r"won't", "will not", text)
    text = re.sub(r"don’t", "do not", text)
    text = re.sub(r"can't", "can not", text)
    text = re.sub(r"im ", "i am", text)
    text = re.sub(r"yo ", "you ",text)
    text = re.sub(r"doesn’t", "does not",text)
    text = re.sub(r"n\'t", " not", text)
    text = re.sub(r"\'re", " are", text)
    text = re.sub(r"\'s", " is", text)
    text = re.sub(r"\'d", " would", text)
    text = re.sub(r"\'ll", " will", text)
    text = re.sub(r"\'t", " not", text)
    text = re.sub(r"\'ve", " have", text)
    text = re.sub(r"\'m", " am", text)
    text = re.sub(r"<br>", " ", text)
    text = re.sub(r'http\S+', '', text) #removing urls
    return text

# Lowercasing the alphabets
df['Review'] = df['Review'].apply(lambda x : x.lower())
df['Review'] = df['Review'].apply(lambda x : decontracted(x))

# Removing punctuations from the review
df['Review'] = df['Review'].str.replace('[^\w\s]','')
df['Review'] = df['Review'].str.replace('\n',' ')

In [15]:
# Removing all the stopwords
stop = stopwords.words('english')
df['Review'] = df['Review'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

In [16]:
df['Review'][0]

'excellent damnnn product amazing super smooth water like display loved'

Lemmatization

In [17]:
# Defining functiom to convert nltk tag to wordnet tags
def nltk_tag_to_wordnet_tag(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:
        return None
    
# Defining function to lemmatize our text
def lemmatize_sentence(sentence):
    # tokenize the sentence and find the pos_tag
    nltk_tagged = nltk.pos_tag(nltk.word_tokenize(sentence))
    # tuple of (token, wordnet_tag)
    wordnet_tagged = map(lambda x : (x[0], nltk_tag_to_wordnet_tag(x[1])), nltk_tagged)
    lemmatize_sentence = []
    for word, tag in wordnet_tagged:
        if tag is None:
            lemmatize_sentence.append(word)
        else:
            lemmatize_sentence.append(lemmatizer.lemmatize(word,tag))
    return " ".join(lemmatize_sentence)    

df['Review'] = df['Review'].apply(lambda x : lemmatize_sentence(x))

In [18]:
df['Review'][0]

'excellent damnnn product amaze super smooth water like display love'

Text Normalization - Standardization

In [19]:
# Noise removal function
def scrub_words(text):
    # remove HTML markup
    text = re.sub("(<.*?>)", "", text)
    # remove non-ascii and digits
    text = re.sub("(\\W)", " ", text)
    text = re.sub("(\\d)", "", text)
    # remove white space
    text = text.strip()
    return text

df['Review'] = df['Review'].apply(lambda x : scrub_words(x))

In [20]:
df['Review'][0]

'excellent damnnn product amaze super smooth water like display love'

Word Counts

In [21]:
# Creating column for word counts in the review text
df['Review_WC'] = df['Review'].apply(lambda x: len(str(x).split(' ')))
df[['Review_WC', 'Review']].head(10)

Review_WC                                             Review
0         10  excellent damnnn product amaze super smooth wa...
1         12  mindblowing purchase good laptop stylish compa...
2         19  simply awesome really much good work faster ex...
3         40  nice product everything fine display awesome k...
4         27  worth money product good screen average build ...
5         10  job pack goodnot pre instal windowdo buy batte...
6          5             awesome excellent product good quality
7          4                       perfect product good product
8         25  good smooth performance good daily casual use ...
9          2                                       awesome good

In [22]:
# Density plot and histogram of all word count
plt.figure(figsize=(10,7))
sns.distplot(df['Review_WC'], hist = True, kde = True,
            bins = int(180/5), color = 'darkblue',
            hist_kws = {'edgecolor':'black'},
            kde_kws = {'linewidth':4})
plt.show()

Character Counts

In [23]:
# Creating column for character counts in the review text
df['Review_CC'] = df['Review'].str.len()
df[['Review_CC','Review']].head(10)

Review_CC                                             Review
0         67  excellent damnnn product amaze super smooth wa...
1         91  mindblowing purchase good laptop stylish compa...
2        129  simply awesome really much good work faster ex...
3        225  nice product everything fine display awesome k...
4        167  worth money product good screen average build ...
5         60  job pack goodnot pre instal windowdo buy batte...
6         38             awesome excellent product good quality
7         28                       perfect product good product
8        166  good smooth performance good daily casual use ...
9         12                                       awesome good

In [24]:
# Density plot and histogram of all character count
plt.figure(figsize=(10,7))
sns.distplot(df['Review_CC'], hist = True, kde = True,
            bins = int(180/5), color = 'darkblue',
            hist_kws = {'edgecolor':'black'},
            kde_kws = {'linewidth':4})
plt.show()


In [27]:
# Applying zscore to remove outliers
z_score = zscore(df[['Review_WC']])
abs_z_score = np.abs(z_score)
filtering_entry = (abs_z_score < 3).all(axis = 1)
df = df[filtering_entry]
print("We have {} Rows and {} Columns in our dataframe after removing outliers".format(df.shape[0], df.shape[1]))

We have 21457 Rows and 6 Columns in our dataframe after removing outliers


In [28]:
pandas_profiling.ProfileReport(df)

TypeError: concat() got an unexpected keyword argument 'join_axes'

In [29]:
# Density plot and histogram of all word count
plt.figure(figsize=(10,7))
sns.distplot(df['Review_WC'], hist = True, kde = True,
            bins = int(180/5), color = 'darkblue',
            hist_kws = {'edgecolor':'black'},
            kde_kws = {'linewidth':4})
plt.show()

In [30]:
# Density plot and histogram of all character count
plt.figure(figsize=(10,7))
sns.distplot(df['Review_CC'], hist = True, kde = True,
            bins = int(180/5), color = 'darkblue',
            hist_kws = {'edgecolor':'black'},
            kde_kws = {'linewidth':4})
plt.show()


In [31]:
# Checking the ratings column details using count plot
x = 'Ratings'
fig, ax = plt.subplots(1,1,figsize=(10,8))
sns.countplot(x=x,data=df,ax=ax)
p=0
for i in ax.patches:
    q = i.get_height()/2
    val = i.get_height()
    ratio = round(val*100/len(df),2)
    prn = f"{val}\n({ratio}%)"
    ax.text(p,q,prn,ha="center",color="white",rotation=0,fontweight="bold",fontsize="13")
    p += 1
    
plt.title("Count Plot: rating")
plt.show()

In [32]:
# Checking review word count distribution for each rating
ratings = np.sort(df.Ratings.unique())
cols = 3
rows = len(ratings)//cols
if rows % cols != 0:
    rows += 1
    
fig = plt.figure(figsize=(20,10))
plt.subplots_adjust(hspace=0.3, wspace=0.2)
p = 1
colors = [(1,0,0,1),(0.6,0.2,0,1),(0.4,0.5,0,1),(0.2,0.7,0,1),(0,1,0.1,1)]
for i in ratings:
    axis = fig.add_subplot(rows,cols,p)
    sns.distplot(df.Review_WC[df.Ratings==i], ax=axis, label=f"For Rating: {i}", color=colors[i-1])
    axis.set_xlabel(f"Review Word Count")
    axis.legend()
    p += 1
    
plt.show()

In [33]:
# Checking review character count distribution for each rating
ratings = np.sort(df.Ratings.unique())
cols = 3
rows = len(ratings)//cols
if rows % cols != 0:
    rows += 1
    
fig = plt.figure(figsize=(20,10))
plt.subplots_adjust(hspace=0.3, wspace=0.2)
p = 1
colors = [(1,0,0,1),(0.6,0.2,0,1),(0.4,0.5,0,1),(0.2,0.7,0,1),(0,1,0.1,1)]
for i in ratings:
    axis = fig.add_subplot(rows,cols,p)
    sns.distplot(df.Review_CC[df.Ratings==i], ax=axis, label=f"For Rating: {i}", color=colors[i-1])
    axis.set_xlabel(f"Review Character Count")
    axis.legend()
    p += 1
    
plt.show()

In [34]:
# Getting insight of loud words in each rating
cols = 2
ratings = np.sort(df.Ratings.unique())
rows = len(ratings)//2
if len(ratings) % cols != 0:
    rows += 1    
fig = plt.figure(figsize=(15,20))
plt.subplots_adjust(hspace=0.3)
p = 1
for i in ratings:
    word_cloud = WordCloud(height=800, width=1000, background_color="white", max_words=50).generate(' '.join(df.Review[df.Ratings==i]))
    axis = fig.add_subplot(rows,cols,p)
    axis.set_title(f"WordCloud for Rating: {i}\n")
    axis.imshow(word_cloud)
    for spine in axis.spines.values():
        spine.set_edgecolor('r')
    axis.set_xticks([])
    axis.set_yticks([])
    
    plt.tight_layout(pad=5)
    p += 1    
plt.show()

NameError: name 'WordCloud' is not defined

In [35]:
# Checking the count of target column values
plt.figure(figsize=(15,7))
sns.countplot(df['Ratings'])
print(df.Ratings.value_counts())
plt.show()

5    13403
4     4075
1     2156
3     1393
2      430
Name: Ratings, dtype: int64


In [36]:
# shuffling the entire data set
df = df.sample(frac=1).reset_index(drop=True)
df

Review_title  \
0                 Must buy!   
1         Worth every penny   
2                 Fabulous!   
3                 Brilliant   
4                 Just wow!   
...                     ...   
21452    Highly recommended   
21453             Hated it!   
21454             Fabulous!   
21455        Decent product   
21456  Good quality product   

                                             Review_text  Ratings  \
0      Best monitor. Product is good. Big screen. Del...        5   
1                 best products ever in watch\nlets rock        5   
2                                           Nice product        5   
3                              best laptop at this price        5   
4      Very nice product....\nI attracted with its be...        5   
...                                                  ...      ...   
21452                                 Perfect watch...💜💜        5   
21453  Raise to wake is not very sensitive, can't tur...        1   
21454                             It's wonderful product        5   
21455  Thanks to flipkart...... because this product ...        3   
21456                                              Super        4   

                                                  Review  Review_WC  Review_CC  
0      must buy best monitor product good big screen ...         13         74  
1      worth every penny best product ever watch let ...          9         50  
2                                  fabulous nice product          3         21  
3                            brilliant best laptop price          4         27  
4      wow nice product attract beauty look wise look...         11         63  
...                                                  ...        ...        ...  
21452                   highly recommended perfect watch          4         32  
21453  hat raise wake sensitive turn heart rate monit...         27        172  
21454                         fabulous wonderful product          3         26  
21455  decent product thanks flipkart product habitin...         15        106  
21456                         good quality product super          4         26  

[21457 rows x 6 columns]

In [37]:
# Select data from every Ratings category
df1 = df[df['Ratings']==1][0:7356]
df2 = df[df['Ratings']==2][0:7356]
df3 = df[df['Ratings']==3][0:7356]
df4 = df[df['Ratings']==4][0:7356]
df5 = df[df['Ratings']==5][0:7356]

# Combining all the dataframes into one and shuffling them again
df = pd.concat([df1,df2,df3,df4,df5], ignore_index=True)
df = df.sample(frac=1).reset_index(drop=True)
df

Review_title  \
0                                            Very Good   
1                                      Worth the money   
2                                         Nice product   
3                                       Simply awesome   
4                                       Simply awesome   
...                                                ...   
15405                                             Fair   
15406                                        Just okay   
15407                                Terrific purchase   
15408                                           Super!   
15409  Waste of money.......go for other better option   

                                             Review_text  Ratings  \
0        Monitor is good and bright, serves the purpose.        4   
1      It is okay for this price, evident lag when th...        4   
2                                                   Good        4   
3                          Superb design value for money        5   
4                                          Looks premium        5   
...                                                  ...      ...   
15405  All is good but battery backup is not perfect ...        3   
15406  Spo2 and BP sensors should be more sensible......        3   
15407  Good product and satisfied with the proper pac...        5   
15408              Value of money such a beautiful watch        5   
15409  The display is a yellow-tinted, white color sh...        2   

                                                  Review  Review_WC  Review_CC  
0                  good monitor good bright serf purpose          6         37  
1      worth money okay price evident lag wrist raise...         25        156  
2                                      nice product good          3         17  
3               simply awesome superb design value money          6         40  
4                            simply awesome look premium          4         27  
...                                                  ...        ...        ...  
15405  fair good battery backup perfect connectivity ...          9         64  
15406    okay spo bp sensor sensible otherwise design ok          8         47  
15407  terrific purchase good product satisfy proper ...         14        106  
15408                  super value money beautiful watch          5         33  
15409  waste moneygo good option display yellowtinted...         23        147  

[15410 rows x 6 columns]

In [38]:
# lets Check the count of target column again to confirm the balance with a visual
plt.figure(figsize=(15,7))
sns.countplot(df['Ratings'])
print(df.Ratings.value_counts())
plt.show()

5    7356
4    4075
1    2156
3    1393
2     430
Name: Ratings, dtype: int64


In [39]:
# Function to plot most frequent terms in our Review column
def freq_words(x, terms=30):
    all_words = ' '.join([text for text in x])
    all_words = all_words.split()
    fdist = FreqDist(all_words)
    words_df = pd.DataFrame({'word':list(fdist.keys()),
                             'count':list(fdist.values())})
    # selecting top 30 most frequent words
    dt = words_df.nlargest(columns='count', n=terms)
    plt.figure(figsize=(15,10))
    ax = sns.barplot(data=dt, x='count', y='word')
    ax.set(ylabel = 'Word')
    plt.show()
    
freq_words(df['Review'])    

In [40]:
# Function to plot least frequent terms in our Review column
def rare_words(x, terms=30):
    all_words = ' '.join([text for text in x])
    all_words = all_words.split()
    fdist = FreqDist(all_words)
    words_df = pd.DataFrame({'word':list(fdist.keys()),
                             'count':list(fdist.values())})
    # selecting top 30 least freq rare words
    dt = words_df.nsmallest(columns='count', n=terms)
    plt.figure(figsize=(15,10))
    ax = sns.barplot(data=dt, x='count', y='word')
    ax.set(ylabel = 'Word')
    plt.show()
    
rare_words(df['Review'])    

In [41]:
# Separating features and labels here
x = df['Review']
y = df['Ratings']

In [42]:
# Using the n_gram tfidf vectorizer (Word vectors)
word_vectorizer = TfidfVectorizer(sublinear_tf = True,
                                  strip_accents = 'unicode',
                                  analyzer = 'word',
                                  token_pattern = r'\w{1,}',
                                  stop_words = 'english',
                                  ngram_range = (1,3),
                                  max_features = 100000)
word_vectorizer.fit(x)
train_word_features = word_vectorizer.transform(x)

# Character vectors
char_vectorizer = TfidfVectorizer(sublinear_tf = True,
                                  strip_accents = 'unicode',
                                  analyzer = 'char',
                                  stop_words = 'english',
                                  ngram_range = (2,6),
                                  max_features = 50000)
char_vectorizer.fit(x)
train_char_features = char_vectorizer.transform(x)

# I will now combine both word vectors and character vectors as input for our model
train_features = hstack([train_char_features, train_word_features])

In [43]:
state = 42
x_train, x_test, y_train, y_test = train_test_split(train_features, y, test_size = 0.30, random_state = state)

# Lets check the shapes of traning and test data
print("x_train", x_train.shape)
print("x_test", x_test.shape)
print("y_train", y_train.shape)
print("y_test", y_test.shape)

x_train (10787, 150000)
x_test (4623, 150000)
y_train (10787,)
y_test (4623,)


In [44]:
# Defining the Classification Machine Learning Algorithms
rf = RandomForestClassifier()
lr = LogisticRegression(solver='lbfgs')
svc = LinearSVC()
bnb = BernoulliNB()
mnb = MultinomialNB()
sgd = SGDClassifier()
lgb = LGBMClassifier()
xgb = XGBClassifier(verbosity=0)

# Creating a function to train and test the model with evaluation metrics
def BuiltModel(model):
    print('*'*30+model.__class__.__name__+'*'*30)
    model.fit(x_train, y_train)
    y_pred = model.predict(x_train)
    pred = model.predict(x_test)
    accuracy = accuracy_score(y_test, pred)*100
    print(f"ACCURACY SCORE PERCENTAGE:", accuracy)
    # Confusion matrix and Classification report
    print(f"CLASSIFICATION REPORT: \n {classification_report(y_test, pred)}")
    print(f"CONFUSION MATRIX: \n {confusion_matrix(y_test, pred)}\n")
    print("-"*120)
    print("\n")

Training and testing of all the classification algorithms

In [45]:
for model in [lr,svc,bnb,mnb,sgd,rf,xgb,lgb]:
    BuiltModel(model)

******************************LogisticRegression******************************
ACCURACY SCORE PERCENTAGE: 95.80359074194246
CLASSIFICATION REPORT: 
               precision    recall  f1-score   support

           1       0.97      1.00      0.98       647
           2       0.99      0.80      0.88       122
           3       0.99      0.84      0.91       408
           4       0.94      0.95      0.94      1238
           5       0.96      0.98      0.97      2208

    accuracy                           0.96      4623
   macro avg       0.97      0.91      0.94      4623
weighted avg       0.96      0.96      0.96      4623

CONFUSION MATRIX: 
 [[ 644    0    0    1    2]
 [  12   97    1    7    5]
 [   8    1  342   36   21]
 [   0    0    3 1174   61]
 [   2    0    1   33 2172]]

------------------------------------------------------------------------------------------------------------------------


******************************LinearSVC******************************
ACCURAC

Cross validation score for best score models

In [46]:
# I am checking cross-validation score only for those algorithms which are giving us better accuracies

def cross_val(model):
    print('*'*30+model.__class__.__name__+'*'*30)
    scores = cross_val_score(model,train_features,y, cv = 3).mean()*100
    print("Cross validation score:", scores)
    print("\n")
    
for model in [lr,svc,sgd,rf,lgb,xgb]:
    cross_val(model)    

******************************LogisticRegression******************************
Cross validation score: 95.77547675518417


******************************LinearSVC******************************
Cross validation score: 96.6645039621535


******************************SGDClassifier******************************
Cross validation score: 96.71641493483536


******************************RandomForestClassifier******************************
Cross validation score: 96.0090710786142


******************************LGBMClassifier******************************
Cross validation score: 97.59895579703861


******************************XGBClassifier******************************
Cross validation score: 97.45619683193479




HyperParameter Tuning

In [47]:
# Lets select the different parameters for tuning our best model (RandomForestClassifier)
grid_params = {'n_estimators':[100,200],
               'criterion':['gini','entropy'],
               'max_depth': [500,800],
               'bootstrap':[True,False]}

# Train the model with given parameters using GridSearchCV
GSCV =  GridSearchCV(rf, grid_params, cv=3, verbose=3)
GSCV.fit(x_train, y_train)

Fitting 3 folds for each of 16 candidates, totalling 48 fits
[CV 1/3] END bootstrap=True, criterion=gini, max_depth=500, n_estimators=100; total time=  32.9s
[CV 2/3] END bootstrap=True, criterion=gini, max_depth=500, n_estimators=100; total time=  33.1s
[CV 3/3] END bootstrap=True, criterion=gini, max_depth=500, n_estimators=100; total time=  35.5s
[CV 1/3] END bootstrap=True, criterion=gini, max_depth=500, n_estimators=200; total time= 1.1min
[CV 2/3] END bootstrap=True, criterion=gini, max_depth=500, n_estimators=200; total time= 1.1min
[CV 3/3] END bootstrap=True, criterion=gini, max_depth=500, n_estimators=200; total time= 1.2min
[CV 1/3] END bootstrap=True, criterion=gini, max_depth=800, n_estimators=100; total time=  33.3s
[CV 2/3] END bootstrap=True, criterion=gini, max_depth=800, n_estimators=100; total time=  33.2s
[CV 3/3] END bootstrap=True, criterion=gini, max_depth=800, n_estimators=100; total time=  35.0s
[CV 1/3] END bootstrap=True, criterion=gini, max_depth=800, n_esti

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'bootstrap': [True, False],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': [500, 800], 'n_estimators': [100, 200]},
             verbose=3)

In [48]:
GSCV.best_params_ # Selecting the best parameters found by GridSearchCV

{'bootstrap': False,
 'criterion': 'gini',
 'max_depth': 800,
 'n_estimators': 200}

In [49]:
# Final Model with the best chosen parameters list
best_model = RandomForestClassifier(bootstrap=False, criterion="gini", max_depth=800, n_estimators=200)
best_model.fit(x_train,y_train) # fitting data to the best model
pred = best_model.predict(x_test)
accuracy = accuracy_score(y_test, pred)*100
# Printing the accuracy score
print("ACCURACY SCORE:", accuracy)
# Printing the classification report
print(f"\nCLASSIFICATION REPORT: \n {classification_report(y_test, pred)}")
# Printing the Confusion matrix
print(f"\nCONFUSION MATRIX: \n {confusion_matrix(y_test, pred)}")

ACCURACY SCORE: 95.80359074194246

CLASSIFICATION REPORT: 
               precision    recall  f1-score   support

           1       0.98      0.99      0.98       647
           2       1.00      0.83      0.91       122
           3       0.98      0.87      0.92       408
           4       0.96      0.93      0.94      1238
           5       0.95      0.99      0.97      2208

    accuracy                           0.96      4623
   macro avg       0.97      0.92      0.94      4623
weighted avg       0.96      0.96      0.96      4623


CONFUSION MATRIX: 
 [[ 638    0    0    0    9]
 [   8  101    2    3    8]
 [   4    0  355   23   26]
 [   0    0    7 1154   77]
 [   1    0    0   26 2181]]


In [50]:
# Creating a normalized confusion matrix here
skplt.metrics.plot_confusion_matrix(y_test, pred, normalize=True)

<AxesSubplot:title={'center':'Normalized Confusion Matrix'}, xlabel='Predicted label', ylabel='True label'>

Saving the best model

In [51]:
joblib.dump(best_model, "Rating_Prediction_Saved_Model.pkl")

['Rating_Prediction_Saved_Model.pkl']

Loading the final model

In [52]:
Model = joblib.load("Rating_Prediction_Saved_Model.pkl")

In [53]:
# Predicting test data using loaded model
prediction = Model.predict(x_test)
# Analysing Predicted vs Actual results
results = pd.DataFrame()
results['Predicted Review Ratings'] = prediction
results['Actual Review Ratings'] = y
results

Predicted Review Ratings  Actual Review Ratings
0                            5                      4
1                            5                      4
2                            5                      4
3                            4                      5
4                            4                      5
...                        ...                    ...
4618                         4                      3
4619                         1                      5
4620                         1                      3
4621                         5                      1
4622                         5                      4

[4623 rows x 2 columns]

In [54]:
# Converting the dataframe into CSV format and saving it
results.to_csv('PredictedvsActual_Ratings_Results.csv', index=False)

Inference:
Key findings of the study: In this project I have collected data of reviews and ratings for different products from amazon.in and flipkart.com. Then I have done different text processing for reviews column and chose equal number of text from each rating class to eliminate problem of imbalance. By doing different EDA steps I have analyzed the text. We have checked frequently occurring words in our data as well as rarely occurring words. After all these steps I have built function to train and test different algorithms and using various evaluation metrics I have selected Random Forest Classifier for our final model. Finally by doing hyperparameter tuning we got optimum parameters for our final model. And finally we got improved accuracy score for our final model.

Limitations of this work and scope for the future work: As we know the content of text in reviews is totally depends on the reviewer and they may rate differently which is totally depends on that particular person. So it is difficult to predict ratings based on the reviews with higher accuracies. Still we can improve our accuracy by fetching more data and by doing extensive hyperparameter tuning.

Areas of improvement:

Less time complexity
More computational power can be given
More accurate reviews can be given
Many more permutations and combinations in hyper paramter tuning can be used to obtain better parameter list